const GraduatesPortrait: Record<string, Promise<{ default: string }>> = {
  "Edmund Ung Eng Soon": import(
    "assets/images/graduates/Edmund Ung Eng Soon.webp"
  ),
  "Chan Kai Zhe": import("assets/images/graduates/Chan Kai Zhe.webp"),
  "Lim Sin Yin": import("assets/images/graduates/Lim Sin Yin.webp"),
  "Goh Yan Jin": import("assets/images/graduates/Goh Yan Jin.webp"),
  "Goh Yu Xian": import("assets/images/graduates/Goh Yu Xian.webp"),
  "Cheng Ley Hang": import("assets/images/graduates/Cheng Ley Hang.webp"),
  "Leong Weng Yip": import("assets/images/graduates/Leong Weng Yip.webp"),
  "Leong Yong Jian": import("assets/images/graduates/Leong Yong Jian.webp"),
  "Ooi Yen Hoe": import("assets/images/graduates/Ooi Yen Hoe.webp"),
  "Ooi Yao Feng": import("assets/images/graduates/Ooi Yao Feng.webp"),
  "Wong Kar Ni": import("assets/images/graduates/Wong Kar Ni.webp"),
  "Teoh Wei Jing": import("assets/images/graduates/Teoh Wei Jing.webp"),
  "Teng Wei Siang": import("assets/images/graduates/Teng Wei Siang.webp"),
  "Andre Cheong Kai Bin": import(
    "assets/images/graduates/Andre Cheong Kai Bin.webp"
  ),
  "Lee Zhan Yue": import("assets/images/graduates/Lee Zhan Yue.webp"),
  "Tan Su Ru": import("assets/images/graduates/Tan Su Ru.webp"),
  "Soi Yih Leong": import("assets/images/graduates/Soi Yih Leong.webp"),
  "Foo Kae Lyn": import("assets/images/graduates/Foo Kae Lyn.webp"),
  "Tan Wan En": import("assets/images/graduates/Tan Wan En.webp"),
  "Lorenz Yong Jun Jie": import(
    "assets/images/graduates/Lorenz Yong Jun Jie.webp"
  ),
  "Gladys Ooi Hui Ting": import(
    "assets/images/graduates/Gladys Ooi Hui Ting.webp"
  ),
  "Ong Chong Meng": import("assets/images/graduates/Ong Chong Meng.webp"),
  "Lim Wi Chung": import("assets/images/graduates/Lim Wi Chung.webp"),
  "Tan Kim Chui": import("assets/images/graduates/Tan Kim Chui.webp"),
  "Poh Jia Shin": import("assets/images/graduates/Poh Jia Shin.webp"),
  "Ng Yun Han": import("assets/images/graduates/Ng Yun Han.webp"),
  "Kee Yan Shen": import("assets/images/graduates/Kee Yan Shen.webp"),
  "Lee Kah Kheng": import("assets/images/graduates/Lee Kah Kheng.webp"),
  "Chong Kar Fai": import("assets/images/graduates/Chong Kar Fai.webp"),
  "Amelia Marie Theseira": import(
    "assets/images/graduates/Amelia Marie Theseira.webp"
  ),
  "Ching Poh Ling": import("assets/images/graduates/Ching Poh Ling.webp"),
  "Tai Yun Ming": import("assets/images/graduates/Tai Yun Ming.webp"),
  "Alvin Tan Kai-Wen": import("assets/images/graduates/Alvin Tan Kai-Wen.webp"),
  "Loe Pei Yu": import("assets/images/graduates/Loe Pei Yu.webp"),
  "Tan Gim Shen": import("assets/images/graduates/Tan Gim Shen.webp"),
  "Lim Wooi Jie": import("assets/images/graduates/Lim Wooi Jie.webp"),
  "Yung Jia Heng": import("assets/images/graduates/Yung Jia Heng.webp"),
  "Lim Pei Thong": import("assets/images/graduates/Lim Pei Thong.webp"),
  "Brian Lee How Cheng": import(
    "assets/images/graduates/Brian Lee How Cheng.webp"
  ),
  "Sim Wan Ting": import("assets/images/graduates/Sim Wan Ting.webp"),
  "Cheah Hao Yuan": import("assets/images/graduates/Cheah Hao Yuan.webp"),
  "Aiy Siew": import("assets/images/graduates/Aiy Siew.webp"),
  "Kang Kok Wai": import("assets/images/graduates/Kang Kok Wai.webp"),
  "Wong Kok Yew": import("assets/images/graduates/Wong Kok Yew.webp"),
  "Chia Jing Ying": import("assets/images/graduates/Chia Jing Ying.webp"),
  "Lim Jing Yi": import("assets/images/graduates/Lim Jing Yi.webp"),
  "Loh Yee Ching": import("assets/images/graduates/Loh Yee Ching.webp"),
  "Leong Chi Wey": import("assets/images/graduates/Leong Chi Wey.webp"),
  "Lim Shir Lee": import("assets/images/graduates/Lim Shir Lee.webp"),
  "Lim Hooi Jia": import("assets/images/graduates/Lim Hooi Jia.webp"),
  "Kelvin Mong Kok Joe": import(
    "assets/images/graduates/Kelvin Mong Kok Joe.webp"
  ),
  "Chung Zhau Tee": import("assets/images/graduates/Chung Zhau Tee.webp"),
  "Lim Jia Jia": import("assets/images/graduates/Lim Jia Jia.webp"),
  "Tatha Risya": import("assets/images/graduates/Tatha Risya.webp"),
  "P'ng Chun Wei": import("assets/images/graduates/P'ng Chun Wei.webp"),
  "Tan Jian Pin": import("assets/images/graduates/Tan Jian Pin.webp"),
  "Chiang De Min": import("assets/images/graduates/Chiang De Min.webp"),
  "Ang Zhen Yuan": import("assets/images/graduates/Ang Zhen Yuan.webp"),
  "Tan Zhi Han": import("assets/images/graduates/Tan Zhi Han.webp"),
  "Manuela Lee Sze Chi": import(
    "assets/images/graduates/Manuela Lee Sze Chi.webp"
  ),
  "Cheryl Lim Tze Chwin": import(
    "assets/images/graduates/Cheryl Lim Tze Chwin.webp"
  ),
  "Chong Jia Yin": import("assets/images/graduates/Chong Jia Yin.webp"),
  "Leong Yu Hong": import("assets/images/graduates/Leong Yu Hong.webp"),
  "Teh Chee Chia": import("assets/images/graduates/Teh Chee Chia.webp"),
  "Chan Jia Keat": import("assets/images/graduates/Chan Jia Keat.webp"),
  "Shannon Chong Tong Tong": import(
    "assets/images/graduates/Shannon Chong Tong Tong.webp"
  ),
  "Chloe Khoo Pin Han": import(
    "assets/images/graduates/Chloe Khoo Pin Han.webp"
  ),
  "Low Zhi Yu": import("assets/images/graduates/Low Zhi Yu.webp"),
  "Lew Hooy Ye": import("assets/images/graduates/Lew Hooy Ye.webp"),
  "Kh'ng Xin Yen": import("assets/images/graduates/Kh'ng Xin Yen.webp"),
  "Cheng Xiao Ge": import("assets/images/graduates/Cheng Xiao Ge.webp"),
  "Chuan Yeat Ying": import("assets/images/graduates/Chuan Yeat Ying.webp"),
  "Kang Ying Ying": import("assets/images/graduates/Kang Ying Ying.webp"),
  "Ang Qiao Shan": import("assets/images/graduates/Ang Qiao Shan.webp"),
  "Choong Jing Wei": import("assets/images/graduates/Choong Jing Wei.webp"),
  "Lok Xue Min": import("assets/images/graduates/Lok Xue Min.webp"),
  "Ling Jia Sze": import("assets/images/graduates/Ling Jia Sze.webp"),
  "Tan Zi Ying": import("assets/images/graduates/Tan Zi Ying.webp"),
  "Tan Hui Xin": import("assets/images/graduates/Tan Hui Xin.webp"),
  Sunitta: import("assets/images/graduates/Sunitta.webp"),
  "Lee Ming Cher": import("assets/images/graduates/Lee Ming Cher.webp"),
  "Lai Jun Hua": import("assets/images/graduates/Lai Jun Hua.webp"),
  "Ng Weiye": import("assets/images/graduates/Ng Weiye.webp"),
  "Ng Jih Yann": import("assets/images/graduates/Ng Jih Yann.webp"),
  "Chang Chee Wing": import("assets/images/graduates/Chang Chee Wing.webp"),
  "Teoh Jiong Zan": import("assets/images/graduates/Teoh Jiong Zan.webp"),
  "Lizen Lai": import("assets/images/graduates/Lizen Lai.webp"),
  "Ng Pei Chi": import("assets/images/graduates/Ng Pei Chi.webp"),
  "Chang Min Chyi": import("assets/images/graduates/Chang Min Chyi.webp"),
  "Khor Shu Chyi": import("assets/images/graduates/Khor Shu Chyi.webp"),
  "Koay Yu Jia": import("assets/images/graduates/Koay Yu Jia.webp"),
  "Chong Xin Qin": import("assets/images/graduates/Chong Xin Qin.webp"),
  "Foo Jia Yee": import("assets/images/graduates/Foo Jia Yee.webp"),
  "Nicholas Lai Jian Ming": import(
    "assets/images/graduates/Nicholas Lai Jian Ming.webp"
  ),
  "Ong Jing Han": import("assets/images/graduates/Ong Jing Han.webp"),
  "Won Zhi Yih": import("assets/images/graduates/Won Zhi Yih.webp"),
  "Khor Zhi Ying": import("assets/images/graduates/Khor Zhi Ying.webp"),
  "Loo You Ji": import("assets/images/graduates/Loo You Ji.webp"),
  "Chang Qing Xian": import("assets/images/graduates/Chang Qing Xian.webp"),
  "Loh Wei Xing": import("assets/images/graduates/Loh Wei Xing.webp"),
  "Tham Chi Cheng": import("assets/images/graduates/Tham Chi Cheng.webp"),
  "Teh Boon Hao": import("assets/images/graduates/Teh Boon Hao.webp"),
  "Cheng Chu Ling": import("assets/images/graduates/Cheng Chu Ling.webp"),
  "Foo Yue Ying": import("assets/images/graduates/Foo Yue Ying.webp"),
  "Lee Ming Wei": import("assets/images/graduates/Lee Ming Wei.webp"),
  "Soo Yih Ying": import("assets/images/graduates/Soo Yih Ying.webp"),
  "Chui Jia Ying": import("assets/images/graduates/Chui Jia Ying.webp"),
  "Ong Yong Jian": import("assets/images/graduates/Ong Yong Jian.webp"),
  "Teoh Qi Yin": import("assets/images/graduates/Teoh Qi Yin.webp"),
  "Chang Kit Ying": import("assets/images/graduates/Chang Kit Ying.webp"),
  "Toh Yee Han": import("assets/images/graduates/Toh Yee Han.webp"),
  "Soo Kiem Eng": import("assets/images/graduates/Soo Kiem Eng.webp"),
  "Yong Xiu Rong": import("assets/images/graduates/Yong Xiu Rong.webp"),
  "Kok Xin Yean": import("assets/images/graduates/Kok Xin Yean.webp"),
  "Tan Ching Ying": import("assets/images/graduates/Tan Ching Ying.webp"),
  "Chang Zi Xuan": import("assets/images/graduates/Chang Zi Xuan.webp"),
  "Beh Yan Chen": import("assets/images/graduates/Beh Yan Chen.webp"),
  "Tan Min Yi": import("assets/images/graduates/Tan Min Yi.webp"),
  "Goh Sook Jing": import("assets/images/graduates/Goh Sook Jing.webp"),
  "Kok Jia Wei": import("assets/images/graduates/Kok Jia Wei.webp"),
  "Teh Keng Hoong": import("assets/images/graduates/Teh Keng Hoong.webp"),
  "Tan Hui Chee": import("assets/images/graduates/Tan Hui Chee.webp"),
  "Tan Yoong Chang": import("assets/images/graduates/Tan Yoong Chang.webp"),
  "Teoh Poh Lin": import("assets/images/graduates/Teoh Poh Lin.webp"),
  "Chia Jin Soon": import("assets/images/graduates/Chia Jin Soon.webp"),
  "Ng Chin Huan": import("assets/images/graduates/Ng Chin Huan.webp"),
  "Ng Yan Jia": import("assets/images/graduates/Ng Yan Jia.webp"),
  "Teoh Yong Kean": import("assets/images/graduates/Teoh Yong Kean.webp"),
  "Alfred Kuan Ren Hong": import(
    "assets/images/graduates/Alfred Kuan Ren Hong.webp"
  ),
  "Chew Zi Lin": import("assets/images/graduates/Chew Zi Lin.webp"),
  "Tan Qian Ying": import("assets/images/graduates/Tan Qian Ying.webp"),
  "Chin Sin Chee": import("assets/images/graduates/Chin Sin Chee.webp"),
  "Teh Le Ni": import("assets/images/graduates/Teh Le Ni.webp"),
  "Wan Zhi Kai": import("assets/images/graduates/Wan Zhi Kai.webp"),
  "Yiew Kah Ling": import("assets/images/graduates/Yiew Kah Ling.webp"),
  "Elvan Yeoh Yan Shin": import(
    "assets/images/graduates/Elvan Yeoh Yan Shin.webp"
  ),
  "Teoh Han Pinn": import("assets/images/graduates/Teoh Han Pinn.webp"),
  "Chew Li May": import("assets/images/graduates/Chew Li May.webp"),
  "Ooi Jun Hao": import("assets/images/graduates/Ooi Jun Hao.webp"),
  "Ooi Tze P'ng": import("assets/images/graduates/Ooi Tze P'ng.webp"),
  "Tan Ying Shan": import("assets/images/graduates/Tan Ying Shan.webp"),
  "Ng Yen Ting": import("assets/images/graduates/Ng Yen Ting.webp"),
  "Lee Su Khee": import("assets/images/graduates/Lee Su Khee.webp"),
  "Yah Qi Yu": import("assets/images/graduates/Yah Qi Yu.webp"),
  "Gabriel Teh Khai Yang": import(
    "assets/images/graduates/Gabriel Teh Khai Yang.webp"
  ),
  "Tan Shu Chuan": import("assets/images/graduates/Tan Shu Chuan.webp"),
  "Dominic Lim Wei Ren": import(
    "assets/images/graduates/Dominic Lim Wei Ren.webp"
  ),
  "Yuen Wei Hong": import("assets/images/graduates/Yuen Wei Hong.webp"),
  "Chan Ka Chun": import("assets/images/graduates/Chan Ka Chun.webp"),
  "Loh Jing En": import("assets/images/graduates/Loh Jing En.webp"),
  "Goh Su Teng": import("assets/images/graduates/Goh Su Teng.webp"),
  "Leong Lei Yeng": import("assets/images/graduates/Leong Lei Yeng.webp"),
  "Ang Jia Jun": import("assets/images/graduates/Ang Jia Jun.webp"),
  "Khor Heh Yih": import("assets/images/graduates/Khor Heh Yih.webp"),
  "Seow Yi Zhuo": import("assets/images/graduates/Seow Yi Zhuo.webp"),
  "Kang Pin Jen": import("assets/images/graduates/Kang Pin Jen.webp"),
};

export default GraduatesPortrait;
