const GraduatesPortrait: Record<string, Promise<{ default: string }>> = {
  "Edmund Ung Eng Soon": import(
    "assets/images/graduates/Edmund Ung Eng Soon.jpg"
  ),
  "Chan Kai Zhe": import("assets/images/graduates/Chan Kai Zhe.jpg"),
  "Lim Sin Yin": import("assets/images/graduates/Lim Sin Yin.jpg"),
  "Goh Yan Jin": import("assets/images/graduates/Goh Yan Jin.jpg"),
  "Goh Yu Xian": import("assets/images/graduates/Goh Yu Xian.jpg"),
  "Cheng Ley Hang": import("assets/images/graduates/Cheng Ley Hang.jpg"),
  "Leong Weng Yip": import("assets/images/graduates/Leong Weng Yip.jpg"),
  "Leong Yong Jian": import("assets/images/graduates/Leong Yong Jian.jpg"),
  "Ooi Yen Hoe": import("assets/images/graduates/Ooi Yen Hoe.jpg"),
  "Ooi Yao Feng": import("assets/images/graduates/Ooi Yao Feng.jpg"),
  "Wong Kar Ni": import("assets/images/graduates/Wong Kar Ni.jpg"),
  "Teoh Wei Jing": import("assets/images/graduates/Teoh Wei Jing.jpg"),
  "Teng Wei Siang": import("assets/images/graduates/Teng Wei Siang.jpg"),
  "Andre Cheong Kai Bin": import(
    "assets/images/graduates/Andre Cheong Kai Bin.jpg"
  ),
  "Lee Zhan Yue": import("assets/images/graduates/Lee Zhan Yue.jpg"),
  "Tan Su Ru": import("assets/images/graduates/Tan Su Ru.jpg"),
  "Soi Yih Leong": import("assets/images/graduates/Soi Yih Leong.jpg"),
  "Foo Kae Lyn": import("assets/images/graduates/Foo Kae Lyn.jpg"),
  "Tan Wan En": import("assets/images/graduates/Tan Wan En.jpg"),
  "Lorenz Yong Jun Jie": import(
    "assets/images/graduates/Lorenz Yong Jun Jie.jpg"
  ),
  "Gladys Ooi Hui Ting": import(
    "assets/images/graduates/Gladys Ooi Hui Ting.jpg"
  ),
  "Ong Chong Meng": import("assets/images/graduates/Ong Chong Meng.jpg"),
  "Lim Wi Chung": import("assets/images/graduates/Lim Wi Chung.jpg"),
  "Tan Kim Chui": import("assets/images/graduates/Tan Kim Chui.jpg"),
  "Poh Jia Shin": import("assets/images/graduates/Poh Jia Shin.jpg"),
  "Ng Yun Han": import("assets/images/graduates/Ng Yun Han.jpg"),
  "Kee Yan Shen": import("assets/images/graduates/Kee Yan Shen.jpg"),
  "Lee Kah Kheng": import("assets/images/graduates/Lee Kah Kheng.jpg"),
  "Chong Kar Fai": import("assets/images/graduates/Chong Kar Fai.jpg"),
  "Amelia Marie Theseira": import(
    "assets/images/graduates/Amelia Marie Theseira.jpg"
  ),
  "Ching Poh Ling": import("assets/images/graduates/Ching Poh Ling.jpg"),
  "Tai Yun Ming": import("assets/images/graduates/Tai Yun Ming.jpg"),
  "Alvin Tan Kai-Wen": import("assets/images/graduates/Alvin Tan Kai-Wen.jpg"),
  "Loe Pei Yu": import("assets/images/graduates/Loe Pei Yu.jpg"),
  "Tan Gim Shen": import("assets/images/graduates/Tan Gim Shen.jpg"),
  "Lim Wooi Jie": import("assets/images/graduates/Lim Wooi Jie.jpg"),
  "Yung Jia Heng": import("assets/images/graduates/Yung Jia Heng.jpg"),
  "Lim Pei Thong": import("assets/images/graduates/Lim Pei Thong.jpg"),
  "Brian Lee How Cheng": import(
    "assets/images/graduates/Brian Lee How Cheng.jpg"
  ),
  "Sim Wan Ting": import("assets/images/graduates/Sim Wan Ting.jpg"),
  "Cheah Hao Yuan": import("assets/images/graduates/Cheah Hao Yuan.jpg"),
  "Aiy Siew": import("assets/images/graduates/Aiy Siew.jpg"),
  "Kang Kok Wai": import("assets/images/graduates/Kang Kok Wai.jpg"),
  "Wong Kok Yew": import("assets/images/graduates/Wong Kok Yew.jpg"),
  "Chia Jing Ying": import("assets/images/graduates/Chia Jing Ying.jpg"),
  "Lim Jing Yi": import("assets/images/graduates/Lim Jing Yi.jpg"),
  "Loh Yee Ching": import("assets/images/graduates/Loh Yee Ching.jpg"),
  "Leong Chi Wey": import("assets/images/graduates/Leong Chi Wey.jpg"),
  "Lim Shir Lee": import("assets/images/graduates/Lim Shir Lee.jpg"),
  "Lim Hooi Jia": import("assets/images/graduates/Lim Hooi Jia.jpg"),
  "Kelvin Mong Kok Joe": import(
    "assets/images/graduates/Kelvin Mong Kok Joe.jpg"
  ),
  "Chung Zhau Tee": import("assets/images/graduates/Chung Zhau Tee.jpg"),
  "Lim Jia Jia": import("assets/images/graduates/Lim Jia Jia.jpg"),
  "Tatha Risya": import("assets/images/graduates/Tatha Risya.jpg"),
  "P'ng Chun Wei": import("assets/images/graduates/P'ng Chun Wei.jpg"),
  "Tan Jian Pin": import("assets/images/graduates/Tan Jian Pin.jpg"),
  "Chiang De Min": import("assets/images/graduates/Chiang De Min.jpg"),
  "Ang Zhen Yuan": import("assets/images/graduates/Ang Zhen Yuan.jpg"),
  "Tan Zhi Han": import("assets/images/graduates/Tan Zhi Han.jpg"),
  "Manuela Lee Sze Chi": import(
    "assets/images/graduates/Manuela Lee Sze Chi.jpg"
  ),
  "Cheryl Lim Tze Chwin": import(
    "assets/images/graduates/Cheryl Lim Tze Chwin.jpg"
  ),
  "Chong Jia Yin": import("assets/images/graduates/Chong Jia Yin.jpg"),
  "Leong Yu Hong": import("assets/images/graduates/Leong Yu Hong.jpg"),
  "Teh Chee Chia": import("assets/images/graduates/Teh Chee Chia.jpg"),
  "Chan Jia Keat": import("assets/images/graduates/Chan Jia Keat.jpg"),
  "Shannon Chong Tong Tong": import(
    "assets/images/graduates/Shannon Chong Tong Tong.jpg"
  ),
  "Chloe Khoo Pin Han": import(
    "assets/images/graduates/Chloe Khoo Pin Han.jpg"
  ),
  "Low Zhi Yu": import("assets/images/graduates/Low Zhi Yu.jpg"),
  "Lew Hooy Ye": import("assets/images/graduates/Lew Hooy Ye.jpg"),
  "Kh'ng Xin Yen": import("assets/images/graduates/Kh'ng Xin Yen.jpg"),
  "Cheng Xiao Ge": import("assets/images/graduates/Cheng Xiao Ge.jpg"),
  "Chuan Yeat Ying": import("assets/images/graduates/Chuan Yeat Ying.jpg"),
  "Kang Ying Ying": import("assets/images/graduates/Kang Ying Ying.jpg"),
  "Ang Qiao Shan": import("assets/images/graduates/Ang Qiao Shan.jpg"),
  "Choong Jing Wei": import("assets/images/graduates/Choong Jing Wei.jpg"),
  "Lok Xue Min": import("assets/images/graduates/Lok Xue Min.jpg"),
  "Ling Jia Sze": import("assets/images/graduates/Ling Jia Sze.jpg"),
  "Tan Zi Ying": import("assets/images/graduates/Tan Zi Ying.jpg"),
  "Tan Hui Xin": import("assets/images/graduates/Tan Hui Xin.jpg"),
  Sunitta: import("assets/images/graduates/Sunitta.jpg"),
  "Lee Ming Cher": import("assets/images/graduates/Lee Ming Cher.jpg"),
  "Lai Jun Hua": import("assets/images/graduates/Lai Jun Hua.jpg"),
  "Ng Weiye": import("assets/images/graduates/Ng Weiye.jpg"),
  "Ng Jih Yann": import("assets/images/graduates/Ng Jih Yann.jpg"),
  "Chang Chee Wing": import("assets/images/graduates/Chang Chee Wing.jpg"),
  "Teoh Jiong Zan": import("assets/images/graduates/Teoh Jiong Zan.jpg"),
  "Lizen Lai": import("assets/images/graduates/Lizen Lai.jpg"),
  "Ng Pei Chi": import("assets/images/graduates/Ng Pei Chi.jpg"),
  "Chang Min Chyi": import("assets/images/graduates/Chang Min Chyi.jpg"),
  "Khor Shu Chyi": import("assets/images/graduates/Khor Shu Chyi.jpg"),
  "Koay Yu Jia": import("assets/images/graduates/Koay Yu Jia.jpg"),
  "Chong Xin Qin": import("assets/images/graduates/Chong Xin Qin.jpg"),
  "Foo Jia Yee": import("assets/images/graduates/Foo Jia Yee.jpg"),
  "Nicholas Lai Jian Ming": import(
    "assets/images/graduates/Nicholas Lai Jian Ming.jpg"
  ),
  "Ong Jing Han": import("assets/images/graduates/Ong Jing Han.jpg"),
  "Won Zhi Yih": import("assets/images/graduates/Won Zhi Yih.jpg"),
  "Khor Zhi Ying": import("assets/images/graduates/Khor Zhi Ying.jpg"),
  "Loo You Ji": import("assets/images/graduates/Loo You Ji.jpg"),
  "Chang Qing Xian": import("assets/images/graduates/Chang Qing Xian.jpg"),
  "Loh Wei Xing": import("assets/images/graduates/Loh Wei Xing.jpg"),
  "Tham Chi Cheng": import("assets/images/graduates/Tham Chi Cheng.jpg"),
  "Teh Boon Hao": import("assets/images/graduates/Teh Boon Hao.jpg"),
  "Cheng Chu Ling": import("assets/images/graduates/Cheng Chu Ling.jpg"),
  "Foo Yue Ying": import("assets/images/graduates/Foo Yue Ying.jpg"),
  "Lee Ming Wei": import("assets/images/graduates/Lee Ming Wei.jpg"),
  "Soo Yih Ying": import("assets/images/graduates/Soo Yih Ying.jpg"),
  "Chui Jia Ying": import("assets/images/graduates/Chui Jia Ying.jpg"),
  "Ong Yong Jian": import("assets/images/graduates/Ong Yong Jian.jpg"),
  "Teoh Qi Yin": import("assets/images/graduates/Teoh Qi Yin.jpg"),
  "Chang Kit Ying": import("assets/images/graduates/Chang Kit Ying.jpg"),
  "Toh Yee Han": import("assets/images/graduates/Toh Yee Han.jpg"),
  "Soo Kiem Eng": import("assets/images/graduates/Soo Kiem Eng.jpg"),
  "Yong Xiu Rong": import("assets/images/graduates/Yong Xiu Rong.jpg"),
  "Kok Xin Yean": import("assets/images/graduates/Kok Xin Yean.jpg"),
  "Tan Ching Ying": import("assets/images/graduates/Tan Ching Ying.jpg"),
  "Chang Zi Xuan": import("assets/images/graduates/Chang Zi Xuan.jpg"),
  "Beh Yan Chen": import("assets/images/graduates/Beh Yan Chen.jpg"),
  "Tan Min Yi": import("assets/images/graduates/Tan Min Yi.jpg"),
  "Goh Sook Jing": import("assets/images/graduates/Goh Sook Jing.jpg"),
  "Kok Jia Wei": import("assets/images/graduates/Kok Jia Wei.jpg"),
  "Teh Keng Hoong": import("assets/images/graduates/Teh Keng Hoong.jpg"),
  "Tan Hui Chee": import("assets/images/graduates/Tan Hui Chee.jpg"),
  "Tan Yoong Chang": import("assets/images/graduates/Tan Yoong Chang.jpg"),
  "Teoh Poh Lin": import("assets/images/graduates/Teoh Poh Lin.jpg"),
  "Chia Jin Soon": import("assets/images/graduates/Chia Jin Soon.jpg"),
  "Ng Chin Huan": import("assets/images/graduates/Ng Chin Huan.jpg"),
  "Ng Yan Jia": import("assets/images/graduates/Ng Yan Jia.jpg"),
  "Teoh Yong Kean": import("assets/images/graduates/Teoh Yong Kean.jpg"),
  "Alfred Kuan Ren Hong": import(
    "assets/images/graduates/Alfred Kuan Ren Hong.jpg"
  ),
  "Chew Zi Lin": import("assets/images/graduates/Chew Zi Lin.jpg"),
  "Tan Qian Ying": import("assets/images/graduates/Tan Qian Ying.jpg"),
  "Chin Sin Chee": import("assets/images/graduates/Chin Sin Chee.jpg"),
  "Teh Le Ni": import("assets/images/graduates/Teh Le Ni.jpg"),
  "Wan Zhi Kai": import("assets/images/graduates/Wan Zhi Kai.jpg"),
  "Yiew Kah Ling": import("assets/images/graduates/Yiew Kah Ling.jpg"),
  "Elvan Yeoh Yan Shin": import(
    "assets/images/graduates/Elvan Yeoh Yan Shin.jpg"
  ),
  "Teoh Han Pinn": import("assets/images/graduates/Teoh Han Pinn.jpg"),
  "Chew Li May": import("assets/images/graduates/Chew Li May.jpg"),
  "Ooi Jun Hao": import("assets/images/graduates/Ooi Jun Hao.jpg"),
  "Ooi Tze P'ng": import("assets/images/graduates/Ooi Tze P'ng.jpg"),
  "Tan Ying Shan": import("assets/images/graduates/Tan Ying Shan.jpg"),
  "Ng Yen Ting": import("assets/images/graduates/Ng Yen Ting.jpg"),
  "Lee Su Khee": import("assets/images/graduates/Lee Su Khee.jpg"),
  "Yah Qi Yu": import("assets/images/graduates/Yah Qi Yu.jpg"),
  "Gabriel Teh Khai Yang": import(
    "assets/images/graduates/Gabriel Teh Khai Yang.jpg"
  ),
  "Tan Shu Chuan": import("assets/images/graduates/Tan Shu Chuan.jpg"),
  "Dominic Lim Wei Ren": import(
    "assets/images/graduates/Dominic Lim Wei Ren.jpg"
  ),
  "Yuen Wei Hong": import("assets/images/graduates/Yuen Wei Hong.jpg"),
  "Chan Ka Chun": import("assets/images/graduates/Chan Ka Chun.jpg"),
  "Loh Jing En": import("assets/images/graduates/Loh Jing En.jpg"),
  "Goh Su Teng": import("assets/images/graduates/Goh Su Teng.jpg"),
  "Leong Lei Yeng": import("assets/images/graduates/Leong Lei Yeng.jpg"),
  "Ang Jia Jun": import("assets/images/graduates/Ang Jia Jun.jpg"),
  "Khor Heh Yih": import("assets/images/graduates/Khor Heh Yih.jpg"),
  "Seow Yi Zhuo": import("assets/images/graduates/Seow Yi Zhuo.jpg"),
  "Kang Pin Jen": import("assets/images/graduates/Kang Pin Jen.jpg"),
};

export default GraduatesPortrait;
