import Container from "@mui/material/Container";
import Typography from "@mui/material/Typography";
import React from "react";
import FeaturedContent from "./FeaturedContent";
import * as S from "./index.styled";

function Home() {
  return (
    <>
      <S.HeroContainer>
        <S.HeroImg
          fileName="home"
          imgProps={{
            alt: "A group photo of KMPk 16/17 students",
          }}
        />
      </S.HeroContainer>
      <Container>
        <S.AboutBox>
          <Typography variant="h3" gutterBottom textAlign="center">
            醇憶 Grad Mag
          </Typography>
          <br />
          <Typography variant="body1" gutterBottom textAlign="center">
            In halls of learning, friendships bloom,
            <br />
            A tapestry of memories, a sweet perfume.
            <br />
            As we stand on the brink of a new sunrise,
            <br />
            Reflecting on moments that made us wise.
            <br />
          </Typography>
          <br />
          <Typography variant="body1" gutterBottom textAlign="center">
            In the pages of our shared history,
            <br />
            Laughter echoes, a cherished melody.
            <br />
            Through late-night studies and early light,
            <br />
            Friends stood by, making every burden light.
            <br />
          </Typography>
          <br />
          <Typography variant="body1" gutterBottom textAlign="center">
            In the classrooms where dreams took flight,
            <br />
            We found allies, their presence bright.
            <br />
            Through challenges faced and triumphs won,
            <br />
            Together we faced the setting sun.
            <br />
          </Typography>
          <br />
          <Typography variant="body1" gutterBottom textAlign="center">
            Through seasons changing, friendships grew,
            <br />
            Roots deepened, like morning dew.
            <br />
            Through exams and projects, stress and glee,
            <br />
            Hand in hand, we faced what would be.
            <br />
          </Typography>
          <br />
          <Typography variant="body1" gutterBottom textAlign="center">
            Now, in caps and gowns, we stand so tall,
            <br />
            Ready to heed the future&apos;s call.
            <br />
            Yet, let&apos;s not forget the ties that bind,
            <br />
            The friendships formed, one of a kind.
            <br />
          </Typography>
          <br />
          <Typography variant="body1" gutterBottom textAlign="center">
            In the yearbook of life, our chapter&apos;s end,
            <br />
            But the echoes of our laughter, they&apos;ll transcend.
            <br />
            The memories we made, a priceless treasure,
            <br />
            Fuel for the journey, a source of pleasure.
            <br />
          </Typography>
          <br />
          <Typography variant="body1" gutterBottom textAlign="center">
            So here&apos;s to you, my dear comrade,
            <br />
            For the times we laughed and times we had.
            <br />
            As we embark on paths anew,
            <br />
            May the bond of friendship ever true.
            <br />
          </Typography>
          <br />
          <Typography variant="body1" gutterBottom textAlign="center">
            In the tapestry of life, we leave our mark,
            <br />
            A legacy of friendship, vibrant and stark.
            <br />
            So, here&apos;s to us, the Class of 16/17,
            <br />
            Forever bound by memories, forever a team.
            <br />
          </Typography>
          <br />
          <Typography variant="body2" gutterBottom textAlign="right">
            This poem is generated by AI
          </Typography>
        </S.AboutBox>
        <FeaturedContent />
      </Container>
    </>
  );
}

export default Home;
