name: Deploy to Firebase Hosting Staging on Labeled
on:
  pull_request:
    types:
      - labeled
jobs:
  deploy_staging_preview:
    if: |
      '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
      && github.event.label.name == 'need-preview'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_OURPROMISE }}"
          projectId: ourpromise
